package com.example.bankomat.entity.enums;

public enum PermissionEnum {
    READ_ALL_EMPLOYEE, READ_ONE_EMPLOYEE, ADD_EMPLOYEE, DELETE_EMPLOYEE, EDIT_EMPLOYEE, EMPLOYEE_CRUD,
    READ_ONE_BANKOMAT, READ_ALL_BANKOMAT, DELETE_BANKOMAT, EDIT_BANKOMAT, ADD_BANKOMAT, MONEY_COUNT, BANKOMAT_CRUD,
    READ_ALL_CARD, READ_ONE_CARD, ADD_CARD, EDIT_CARD, CARD_BLOCK, CARD_UNBLOCK, CARD_CRUD,
    MONEY_ADD, MONEY_DELETE, FILL_UP_ATM, MONEY_CRUD

}
